// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwxttiysuykwjhicgwrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3eHR0aXlzdXlrd2poaWNnd3JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4MDc3NjAsImV4cCI6MjA4NjM4Mzc2MH0.qEHdclMbbj9WLtdVLFNtWxzP9Z28MmsUjjH11BcX0sc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});